// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWebMvc.Data;

#nullable disable

namespace SalesWebMvc.Migrations
{
    [DbContext(typeof(SalesWebMvcContext))]
    partial class SalesWebMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesWebMvc.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Foods"
                        });
                });

            modelBuilder.Entity("SalesWebMvc.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("SalesRecord");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.90000000000001,
                            Date = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 947.62,
                            Date = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 882.50999999999999,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 575.08000000000004,
                            Date = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 486.29000000000002,
                            Date = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 8,
                            Status = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 412.94,
                            Date = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 919.79999999999995,
                            Date = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 852.85000000000002,
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 103.36,
                            Date = new DateTime(2024, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 536.45000000000005,
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 13,
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 538.44000000000005,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 15,
                            Status = 2
                        });
                });

            modelBuilder.Entity("SalesWebMvc.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 2500.0,
                            BirthDate = new DateTime(1995, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "maria@gmail.com",
                            Name = "Maria Betania"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 3509.52,
                            BirthDate = new DateTime(1997, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "angelafreeman@hotmail.com",
                            Name = "Noah Taylor"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 3468.9400000000001,
                            BirthDate = new DateTime(1969, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "williamscarl@yahoo.com",
                            Name = "Michelle Fischer"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 2286.02,
                            BirthDate = new DateTime(1993, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "maryhill@sims.com",
                            Name = "Joseph Gallegos"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 3134.9099999999999,
                            BirthDate = new DateTime(2003, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "qlara@costa.com",
                            Name = "Randall Chapman"
                        },
                        new
                        {
                            Id = 6,
                            BaseSalary = 2327.9499999999998,
                            BirthDate = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "juan97@yahoo.com",
                            Name = "Jason Ortiz"
                        },
                        new
                        {
                            Id = 7,
                            BaseSalary = 2142.6700000000001,
                            BirthDate = new DateTime(1989, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "sampsondarin@adams-armstrong.net",
                            Name = "Carl Roberts"
                        },
                        new
                        {
                            Id = 8,
                            BaseSalary = 2459.52,
                            BirthDate = new DateTime(1973, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "paulvaldez@maxwell.org",
                            Name = "Austin Smith"
                        },
                        new
                        {
                            Id = 9,
                            BaseSalary = 4726.29,
                            BirthDate = new DateTime(1979, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "melissa87@mooney.com",
                            Name = "Thomas Rodriguez"
                        },
                        new
                        {
                            Id = 10,
                            BaseSalary = 2367.1700000000001,
                            BirthDate = new DateTime(1997, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "shawn91@weaver.com",
                            Name = "Kelly Salas"
                        },
                        new
                        {
                            Id = 11,
                            BaseSalary = 3926.3600000000001,
                            BirthDate = new DateTime(1983, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "osmith@scott-lucas.com",
                            Name = "James Garcia"
                        },
                        new
                        {
                            Id = 12,
                            BaseSalary = 2520.3800000000001,
                            BirthDate = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "kelseycastaneda@gmail.com",
                            Name = "Sara Burke"
                        },
                        new
                        {
                            Id = 13,
                            BaseSalary = 2743.77,
                            BirthDate = new DateTime(1961, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "brett72@blake.com",
                            Name = "Carol Miller"
                        },
                        new
                        {
                            Id = 14,
                            BaseSalary = 3184.5,
                            BirthDate = new DateTime(1999, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "hfrank@perez-smith.com",
                            Name = "Michael Freeman"
                        },
                        new
                        {
                            Id = 15,
                            BaseSalary = 4813.7399999999998,
                            BirthDate = new DateTime(1985, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "mitchell21@yahoo.com",
                            Name = "Alicia Martinez"
                        },
                        new
                        {
                            Id = 16,
                            BaseSalary = 3666.5500000000002,
                            BirthDate = new DateTime(1984, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "nicholasharmon@cruz-evans.biz",
                            Name = "Sandra Anderson"
                        },
                        new
                        {
                            Id = 17,
                            BaseSalary = 4064.5500000000002,
                            BirthDate = new DateTime(1996, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "lydia44@duncan-bush.info",
                            Name = "Brandon Young"
                        },
                        new
                        {
                            Id = 18,
                            BaseSalary = 2538.6700000000001,
                            BirthDate = new DateTime(1994, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ianderson@hotmail.com",
                            Name = "Nicholas Reed"
                        },
                        new
                        {
                            Id = 19,
                            BaseSalary = 2408.5599999999999,
                            BirthDate = new DateTime(1998, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "robert49@yahoo.com",
                            Name = "John Cook"
                        },
                        new
                        {
                            Id = 20,
                            BaseSalary = 3923.1900000000001,
                            BirthDate = new DateTime(1984, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "dhudson@hotmail.com",
                            Name = "Amanda Bell"
                        },
                        new
                        {
                            Id = 21,
                            BaseSalary = 4293.6300000000001,
                            BirthDate = new DateTime(1978, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "nmorris@gmail.com",
                            Name = "David Johnson"
                        },
                        new
                        {
                            Id = 22,
                            BaseSalary = 2558.6700000000001,
                            BirthDate = new DateTime(1982, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "jacobpatrick@moses.com",
                            Name = "Paul Evans"
                        },
                        new
                        {
                            Id = 23,
                            BaseSalary = 4185.0,
                            BirthDate = new DateTime(1989, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "kenneth66@hotmail.com",
                            Name = "Amanda Murphy"
                        },
                        new
                        {
                            Id = 24,
                            BaseSalary = 2975.6100000000001,
                            BirthDate = new DateTime(1979, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "kgriffin@hotmail.com",
                            Name = "Robyn Hobbs"
                        },
                        new
                        {
                            Id = 25,
                            BaseSalary = 4133.3299999999999,
                            BirthDate = new DateTime(1986, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "kevinmcfarland@rice.org",
                            Name = "Ann Berry"
                        },
                        new
                        {
                            Id = 26,
                            BaseSalary = 3575.8899999999999,
                            BirthDate = new DateTime(1996, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "valerie71@johnston-mitchell.com",
                            Name = "Karen Clark"
                        },
                        new
                        {
                            Id = 27,
                            BaseSalary = 3662.0700000000002,
                            BirthDate = new DateTime(1979, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "rreed@carroll.com",
                            Name = "Amber Gonzalez"
                        });
                });

            modelBuilder.Entity("SalesWebMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "1234",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("SalesWebMvc.Models.SalesRecord", b =>
                {
                    b.HasOne("SalesWebMvc.Models.Seller", "Seller")
                        .WithMany("SalesRecords")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Seller", b =>
                {
                    b.HasOne("SalesWebMvc.Models.Department", "Department")
                        .WithMany("Sellers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Department", b =>
                {
                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Seller", b =>
                {
                    b.Navigation("SalesRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
